### ISSUE TITLE
Упрощайте: return i == 14

### ISSUE THREAD

**Issue by coursar** [banch0/indexes#2]
https://github.com/banch0/indexes/blob/a3a44661a50ef7c27315d3017f8e67a925df10f4/indexes_test.go#L99-L102

**Comment by banch0** [comment]
Извините, просто не понял, что именно упростить? Убрать цифри? Или вообще изменить if ?

**Comment by coursar** [comment]
Вот это:

```go
 if i == 14 { 
 	return true 
 } 
 return false 
```
надо заменить на:
```
 return i == 14
```
